### ISSUE TITLE
Выбрать инструмент для трекинга задач

### ISSUE THREAD

**Issue by sd01dev** [Mohan-Snow/event-notification-bot#1]
Рассмотреть различные варианты для отслеживания задач по разработке сервиса и выбрать инструмент для данного проекта.

Из предложенных вариантов:
1. Github issues
2. Jetbrains space

**Comment by dapmoed** [comment]
Я за простоту - Github issues

**Comment by Mohan-Snow** [comment]
Коллективным голосованием выбран Github issues

**Comment by Mohan-Snow** [comment]
Коллективным голосованием выбран Github issues
