### ISSUE TITLE
Выбрать основные библиотеки для разработки

### ISSUE THREAD

**Issue by sd01dev** [Mohan-Snow/event-notification-bot#2]
Нужно определиться с библиотеками для:

1. Конфигурирования
2. Логгирования
3. Работы с telegram API
4. Работы с БД (билдер, миграции)

**Comment by randomowo** [comment]
Предлагаю для бд и миграций воспользоваться довольно удобной либой bun (orm), а веб сервера (хуки ловить) fiber.

**Comment by randomowo** [comment]
как мне кажется удобнее всего легировать будет удобнее в json формате, так как проще будет анализировать с помощью тулзов типа jq

**Comment by sd01dev** [comment]
В свою очередь предлагаю использовать стандартные решения:
1. Slog/zap для логгирования
2. squirrel/goose для запросов и миграции

Потребуется ли отдельная либа хуки ловить пока не понятно, предложил бы начать со стандартной либы и если будет что-то не устраивать уже перекатываться на кастомные

**Comment by randomowo** [comment]
если логировать в json, то zerolog может быть получше (самый быстрый по сути), хотя по интерфейсу такой де как zap с первого взгялда.

bun умеет в миграции, так что можно только его использовать

**Comment by dapmoed** [comment]
> В свою очередь предлагаю использовать стандартные решения:
> 
> 1. Slog/zap для логгирования
> 2. squirrel/goose для запросов и миграции
> 
> Потребуется ли отдельная либа хуки ловить пока не понятно, предложил бы начать со стандартной либы и если будет что-то не устраивать уже перекатываться на кастомные

На мой взгляд Zap сильно удобнее всего что есть.
Fiber было бы интересно

**Comment by Mohan-Snow** [comment]
Я тоже за то, чтобы для логгирования использовать Zap.

**Comment by Mohan-Snow** [comment]
Конфигурирование: 
1. Viper
2. kelseyhightower/envconfig
3. urfave/cli
4. caarlos0/env

**Comment by Mohan-Snow** [comment]
Конфигурирования -> kelseyhightower/envconfig
Логгирования -> ZAP
Работы с telegram API -> https://github.com/go-telegram-bot-api/telegram-bot-api
Работы с БД (билдер, миграции) -> squirrel и goose
Router -> Fiber
